//
//  CDDoctorWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 15/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreData

class CDDoctorWorker
{
  // MARK: Business Logic
  
    func deleteConsult(entity: CDConsultData, completionHandler: (success: Bool) -> Void) {
        do {
            CDCoreDataStack.sharedInstance.managedObjectContext.deleteObject(entity)
            try CDCoreDataStack.sharedInstance.managedObjectContext.save()
            completionHandler(success: true)
        } catch {
            print(error)
            completionHandler(success: false)
        }
    }
}
