//
//  CDDoctorModels.swift
//  ControlaDor
//
//  Created by Isaías Lima on 15/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CDDoctorRequest
{
}

struct CDDoctorResponse
{
    var entities: [CDConsultData]!
}

struct CDDoctorViewModel
{
    var contacts: [CDUserContact]!
    var images: [[UIImage]]!
    var results: [String]!
}

struct CDConsult
{
    var contact: CDUserContact!
    var images: [UIImage]!
    var results: String!
}

struct CDConsultDeleteRequest {
    var entityData: CDConsult!
}
