//
//  CDDoctorConfigurator.swift
//  ControlaDor
//
//  Created by Isaías Lima on 15/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension CDDoctorViewController: CDDoctorPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension CDDoctorInteractor: CDDoctorViewControllerOutput
{
}

extension CDDoctorPresenter: CDDoctorInteractorOutput
{
}

class CDDoctorConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: CDDoctorConfigurator
  {
    struct Static {
      static var instance: CDDoctorConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = CDDoctorConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: CDDoctorViewController)
  {
    let router = CDDoctorRouter()
    router.viewController = viewController
    
    let presenter = CDDoctorPresenter()
    presenter.output = viewController
    
    let interactor = CDDoctorInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
