//
//  CDPainDataWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 09/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreData

class CDPainDataWorker
{
  // MARK: Business Logic
    var local: String
    var intensity: Double
    var date: NSDate!

  init(request: CDPainDatumRequest)
  {
    local = request.local
    intensity = request.intensity
  }

  init(request: CDPainDatumDeleteRequest) {
    local = request.local
    intensity = request.intensity
    date = request.date
  }
  
  func createPainDatum(completionHandler: (success: Bool) -> Void)
  {
    let painDatum = NSEntityDescription.insertNewObjectForEntityForName("CDPainDatum", inManagedObjectContext: CDCoreDataStack.sharedInstance.managedObjectContext) as! CDPainDatum
    painDatum.date = NSDate()
    painDatum.intensity = intensity
    painDatum.local = local

    do {
        try CDCoreDataStack.sharedInstance.managedObjectContext.save()
        completionHandler(success: true)
    } catch {
        print(error)
        completionHandler(success: false)
    }
  }

  func deletePainDatum(entity: CDPainDatum, completionHandler: (success: Bool) -> Void) {
    do {
        CDCoreDataStack.sharedInstance.managedObjectContext.deleteObject(entity)
        try CDCoreDataStack.sharedInstance.managedObjectContext.save()
        completionHandler(success: true)
    } catch {
        print(error)
        completionHandler(success: false)
    }
  }
}
