//
//  CDPainDataModels.swift
//  ControlaDor
//
//  Created by Isaías Lima on 09/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CDPainDataRequest
{
    var entityName: String!
}

struct CDPainDataResponse
{
    var painEntity: [CDPainDatum]!
}

struct CDPainDataViewModel
{
    var dates: [NSDate]!
    var intensities: [Double]!
    var locals: [String]!
}

struct CDPainDatumRequest
{
    var intensity: Double
    var local: String
}

struct CDPainDatumDeleteRequest
{
    var date: NSDate!
    var intensity: Double
    var local: String!
}

struct CDPainDataServerRequest
{
    var painData:[(NSDate,Double,String)]!
}
