//
//  CDPainDataConfigurator.swift
//  ControlaDor
//
//  Created by Isaías Lima on 09/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension CDPainDataViewController: CDPainDataPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension CDPainDataInteractor: CDPainDataViewControllerOutput
{
}

extension CDPainDataPresenter: CDPainDataInteractorOutput
{
}

class CDPainDataConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: CDPainDataConfigurator
  {
    struct Static {
      static var instance: CDPainDataConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = CDPainDataConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: CDPainDataViewController)
  {
    let router = CDPainDataRouter()
    router.viewController = viewController
    
    let presenter = CDPainDataPresenter()
    presenter.output = viewController
    
    let interactor = CDPainDataInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
