//
//  CDPersistentStoreWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import CoreData

class CDPersistentStoreWorker
{
    // MARK: Business Logic
    var fetchRequest: NSFetchRequest!

    init(entityName: String) {
        fetchRequest = NSFetchRequest(entityName: entityName)
    }
  
    func makeFetchRequest(responseHandler: (entities: [CDPainDatum]) -> Void) throws
    {
        do {
            let entities = try CDCoreDataStack.sharedInstance.managedObjectContext.executeFetchRequest(fetchRequest) as! [CDPainDatum]
            responseHandler(entities: entities)
        } catch {
            throw error
        }
    }
}
