//
//  CDPersistentStoreWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class CDPersistentStoreWorker
{
    // MARK: Business Logic

    init(stack: CoreDataStack) {
        
    }
  
    func doSomeWork()
    {
        // NOTE: Do the work
    }
}
