//
//  CDUserInteractor.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ResearchKit

protocol CDUserInteractorInput
{
    func requestHealthAndData(request: CDUserRequest)
}

protocol CDUserInteractorOutput
{
    func presentHealthAndData(response: CDUserResponse)
}

class CDUserInteractor: CDUserInteractorInput
{
    var output: CDUserInteractorOutput!
    var worker: CDUserWorker!

    var userHealthData: [NSObject : String]!
    var buttonStrings: [String]!
    var briefPainTask: ORKOrderedTask!
  
    // MARK: Business logic
  
    func requestHealthAndData(request: CDUserRequest)
    {
        // NOTE: Create some Worker to do the work
    
        worker = CDUserWorker()
        worker.fetchHealthAndButtonData { (userHealthData, buttonStrings, briefPainTask) -> Void in
            self.userHealthData = userHealthData
            self.buttonStrings = buttonStrings
            self.briefPainTask = briefPainTask
        }
    
        // NOTE: Pass the result to the Presenter
    
        let response = CDUserResponse(userHealthData: userHealthData , buttonStrings: buttonStrings, briefPainTask: briefPainTask)
        output.presentHealthAndData(response)
    }
}
