//
//  CDUserPresenter.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ResearchKit

protocol CDUserPresenterInput
{
  func presentHealthAndData(response: CDUserResponse)
}

protocol CDUserPresenterOutput: class
{
  func displayDataSource(viewModel: CDUserViewModel)
}

class CDUserPresenter: CDUserPresenterInput
{
  weak var output: CDUserPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentHealthAndData(response: CDUserResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    let healthData = response.userHealthData
    let buttonStrings = response.buttonStrings
    let briefPainTask = response.briefPainTask
    
    let viewModel = CDUserViewModel(userHealthData: healthData , buttonStrings: buttonStrings, briefPainTask: briefPainTask)
    output.displayDataSource(viewModel)
  }
}
