//
//  CDUserModels.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ResearchKit

struct CDUserRequest
{
}

struct CDUserResponse
{
    var userHealthData: [NSObject : String]!
    var buttonStrings: [String]!
    var briefPainTask: ORKOrderedTask!
}

struct CDUserViewModel
{
    var userHealthData: [NSObject : String]!
    var buttonStrings: [String]!
    var briefPainTask: ORKOrderedTask!
}
