//
//  CDUserConfigurator.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension CDUserViewController: CDUserPresenterOutput
{
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    if segue.identifier == "Consulta" {
        router.passDataToNextScene(segue)
    }
  }
}

extension CDUserInteractor: CDUserViewControllerOutput
{
}

extension CDUserPresenter: CDUserInteractorOutput
{
}

class CDUserConfigurator
{
  // MARK: Object lifecycle
  
  class var sharedInstance: CDUserConfigurator
  {
    struct Static {
      static var instance: CDUserConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = CDUserConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: CDUserViewController)
  {
    let router = CDUserRouter()
    router.viewController = viewController
    
    let presenter = CDUserPresenter()
    presenter.output = viewController
    
    let interactor = CDUserInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
