//
//  CDUserWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ResearchKit

class CDUserWorker
{
    // MARK: Business Logic
  
    func fetchHealthAndButtonData(completionHandler: (userHealthData: [NSObject : String] , buttonStrings: [String], briefPainTask: ORKOrderedTask) -> Void)
    {
        let userData = ["Nome" : "Isaías Lima" , "Peso" : "62kg" , "Nascimento" : "11/09/1995" , "e-mail" : "isaiahlima18@gmail.com"]
        let buttonData = ["Inventário breve de dor" , "Marcar consulta"]
        completionHandler(userHealthData: userData, buttonStrings: buttonData, briefPainTask: BriefPainInvetoryTask)
    }
}
