//
//  CDUserWorker.swift
//  ControlaDor
//
//  Created by Isaías Lima on 08/03/16.
//  Copyright (c) 2016 PainController. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ResearchKit

class CDUserWorker
{
    // MARK: Business Logic
  
    func fetchHealthAndButtonData(completionHandler: (userHealthData: [NSObject : String] , buttonStrings: [String], briefPainTask: ORKOrderedTask) -> Void)
    {
        let userData = getUserDefaultsForUserData()
        let buttonData = ["Inventário breve de dor" , "Solicitar consulta"]
        completionHandler(userHealthData: userData, buttonStrings: buttonData, briefPainTask: BriefPainInvetoryTask)
    }

    func getUserDefaultsForUserData() -> [NSObject : String] {
        let userDefaults = NSUserDefaults.standardUserDefaults()
        if let userData = userDefaults.objectForKey("Contact") as? [String : String] {
            return userData
        } else {
            userDefaults.setObject(nil, forKey: "Contact")
            return ["Toque em editar para adicionar dados" : ""]
        }
    }
}
